# Spring config properties
spring.config.import=optional:file:.env[.properties]


# Nome da aplicação
spring.application.name=gerenciador-de-tarefas

# URL de conexão com banco de dados
spring.datasource.url=${POSTGRES_URL}
# Usuário do banco
spring.datasource.username=${POSTGRES_USER}
# Senha do banco de dados
spring.datasource.password=${POSTGRES_PASSWORD}

# Driver do JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto do Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Estratégia de atualização das tabelas
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true

#Formatar log no sql
spring.jpa.properties.hibernate.format_sql=true

# Porta da aplicação
server.port=8080

